include $(THEOS)/makefiles/common.mk

TOOL_NAME = sshtoggled

sshtoggled_FILES = main.m
sshtoggled_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tool.mk
# SUBPROJECTS += sshtoggled
include $(THEOS_MAKE_PATH)/aggregate.mk
